### ISSUE TITLE
EMail success but not body write

### ISSUE THREAD

**Issue by ghost** [aslarchergore/open-relay#1]
email is sent with success , but appear all clean....
subject only say "test"

![image](https://user-images.githubusercontent.com/40305340/123414299-9f14da80-d5ab-11eb-8556-d1b31961f018.png)

![image](https://user-images.githubusercontent.com/40305340/123410781-991cfa80-d5a7-11eb-8886-b3dfc572175f.png)

**Comment by BuSh1DO** [comment]
solved by changing line "s.send("Subject: RELAY\r\n\r\nHello,\r\nThis is a mail spoofing test.\r\n.\r\n")"

**Comment by ghost** [comment]
s.send("Subject: RELAY\r\n\r\nHello,\r\nThis is a mail spoofing test.\r\n.\r\n")
